sudo: required
services:
- docker
language: java
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
deploy:
- skip_cleanup: true
  on:
    tags: true
  provider: releases
  api_key:
    secure: uFLgV8421j/Qv0y7qtCjsYytAsLYqxycc751rgIy7+BMQ3PcZVmJcaKg47KabsrzCZ59xkfWuZQZvEuj5xzAkRUFdnKF6xasVJiE11xB3PwOjUiq7zqBCU31lvV1xFMtcwtcUS3LCwLLNFQfTkVXwRE2vK7OuDJgHJoG8xH0Gq6SimpF6K+/1mvK7dZvZzlW9qQYgSpjHArSHdQrsonSEoomqEZ/4xbCF9jxcF6yZomXl7cWCkUWNdfG9ht3uUo6rEiEaodmVV0d6r4HtsJDst+BtQtaLyVIxecvWRZJZ2KYKjU/LFEe/HbUnj1eOIKiBmFB6bx9eBQWNou4R821SJzPg1mYtQSxGl0s42S63+uDTFROkU8iKGMlgg9kzvcQNK1FtWOQm4Zn8EUxHD67JzSPrh3bHkxFbKz3g8KymGEGlESdXyvTESIbkGqqVJMdi7rh7S/82zhODB+8YeGyhud5sS7SfG3YVb+lF1Dbn2tq86SJCuGicYY16XdtmAO6beG02mnU383UfGH0jTG2Gxcj1xlCZBx9+WMvL7VOIUNfccjIvTHAQatXFkBsHLYbb6YQJe5QTkvXJQyNr7KWhYWn6xSWQvLUbQRlLfaND+z2h2Rw0vlq9iarXWQ3+LjDoThmS0AFzvsd6lp6jli1cuhRNutOMMBT+EHDVVnW7tU=
  file: build/libs/ansible-plugin-${TRAVIS_TAG}.jar
# - skip_cleanup: true
#   on:
#     branch: master
#     tags: true
#   provider: script
#   script: bash deploy-docker.sh
